name: ui_kit
description: UI Kit module - Common UI components (Buttons, Dialogs, Layouts)
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
