name: router
description: Router module - Navigation and routing using AutoRouter
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.0
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^9.0.0
