name: infrastructure
description: Infrastructure module - Logging and crash monitoring (Logger, Sentry)
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^4.1.3
  sentry_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
