name: core
description: Core module - Environment, Theme, Network configurations
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  image_gallery_saver_plus: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
